### ISSUE TITLE
[Bug] set critical function fails

### ISSUE THREAD

**Issue by atalyaalon** [data-for-change/anyway#2596]
**Describe the bug**

After dataflow failure, I removed "set-critical" [in this pr](https://github.com/data-for-change/anyway/pull/2594).
Seems like a small issue from looking at traceback:
To see failure reason - I'm copying traceback [from this specific flow](https://airflow.anyway.co.il/log?dag_id=update-all-news-flash&task_id=update-all-news-flash&execution_date=2024-03-25T18%3A18%3A41.007945%2B00%3A00&map_index=-1):

```
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "main.py", line 540, in <module>
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     cli(sys.argv[1:])  # pylint: disable=too-many-function-args
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/venv3/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     return self.main(*args, **kwargs)
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/venv3/lib/python3.8/site-packages/click/core.py", line 1055, in main
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     rv = self.invoke(ctx)
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/venv3/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/venv3/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/venv3/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     return ctx.invoke(self.callback, **ctx.params)
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/venv3/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     return __callback(*args, **kwargs)
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "main.py", line 78, in update
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     return news_flash.update_all_in_db(source, news_flash_id, update_cbs_location_only)
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/anyway/anyway/parsers/news_flash.py", line 41, in update_all_in_db
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     newsflash.set_critical()
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/anyway/anyway/models.py", line 906, in set_critical
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     location_info = LocationInfo()
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -   File "/usr/lib/python3.8/typing.py", line 727, in __call__
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO -     raise TypeError(f"Type {self._name} cannot be instantiated; "
[2024-03-25, 18:18:53 UTC] {subprocess.py:93} INFO - TypeError: Type Dict cannot be instantiated; use dict() instead
```

**Comment by atalyaalon** [comment]
@EliorGigi please take a look, only after you finish your current tasks
